// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYhz7ptHaSitrsKwI3D2tE9uLaCVYVDVA',
    appId: '1:76074373768:web:544d71ab99c0ae8446453d',
    messagingSenderId: '76074373768',
    projectId: 'photoapp-85f69',
    authDomain: 'photoapp-85f69.firebaseapp.com',
    storageBucket: 'photoapp-85f69.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByNTVHdY9NMCPu68k2r78D8EA33u03gQQ',
    appId: '1:76074373768:android:6131863fa761db7d46453d',
    messagingSenderId: '76074373768',
    projectId: 'photoapp-85f69',
    storageBucket: 'photoapp-85f69.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuvJbuVbMgycKpwPRiRNZAPMiJaY9PB2M',
    appId: '1:76074373768:ios:3e7a6208b64ead9b46453d',
    messagingSenderId: '76074373768',
    projectId: 'photoapp-85f69',
    storageBucket: 'photoapp-85f69.appspot.com',
    iosClientId: '76074373768-fk89v0kee4tqhpucss8t2adlj221aegj.apps.googleusercontent.com',
    iosBundleId: 'com.example.uberUsersideClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuvJbuVbMgycKpwPRiRNZAPMiJaY9PB2M',
    appId: '1:76074373768:ios:3e7a6208b64ead9b46453d',
    messagingSenderId: '76074373768',
    projectId: 'photoapp-85f69',
    storageBucket: 'photoapp-85f69.appspot.com',
    iosClientId: '76074373768-fk89v0kee4tqhpucss8t2adlj221aegj.apps.googleusercontent.com',
    iosBundleId: 'com.example.uberUsersideClone',
  );
}
